package mz.co.quankee.drools.tax.calculator;

import mz.co.quankee.drools.tax.calculator.domain.dto.EmployeeDto

dialect  "java"

rule "Validate Age - Minor"
    when
        $employee: EmployeeDto( employeeAge < 18 )
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome(0.0),
            setObservation("Employee is a minor. Not allowed to work")
        }
end

rule "Validate Age - Retired"
    when
        $employee: EmployeeDto( employeeAge > 65 )
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome(179990.0),
            setObservation("Employee is retired.")
        }
end

rule "Calculate Salary for 18 an 65  with less than 10000.00"
    when
        $employee: EmployeeDto( (employeeAge >= 18 && employeeAge <= 65) && monthlyIncome < 10000.00)
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome($employee.getMonthlyIncome()),
            setObservation("No taxes apply for this employee")
        }
end

rule "Calculate Salary for 18 and 30 with income between 10000.00 and 20000.00"
    when
        $employee: EmployeeDto((employeeAge >= 18 && employeeAge <= 30) && (monthlyIncome > 10000.00 && monthlyIncome < 20000.00) )
    then
        modify($employee){
            setTax(10.0),
            setNetMonthlyIncome($employee.getMonthlyIncome() - ($employee.getMonthlyIncome() * 0.1)),
            setObservation("Applied Tax of 10.0%")
        }
end

rule "Calculate Salary for 18 and 30 with income between 20000.00 and 40000.00"
    when
        $employee: EmployeeDto((employeeAge >= 18 && employeeAge <= 30) && (monthlyIncome > 20000.00 && monthlyIncome < 40000.00) )
    then
        modify($employee){
            setTax(15.0),
            setNetMonthlyIncome($employee.getMonthlyIncome() - ($employee.getMonthlyIncome() * 0.15)),
            setObservation("Applied Tax of 15.0%")
        }
end

rule "Calculate Salary for 30 and 60 with income between 10000.00 and 20000.00"
    when
        $employee: EmployeeDto((employeeAge > 30 && employeeAge <= 65) && (monthlyIncome > 10000.00 && monthlyIncome < 20000.00) )
    then
        modify($employee){
            setTax(20.0),
            setNetMonthlyIncome($employee.getMonthlyIncome() - ($employee.getMonthlyIncome() * 0.2)),
            setObservation("Applied Tax of 20.0%")
        }
end

rule "Calculate Salary for 30 and 60 with income between 20000.00 and 40000.00"
    when
        $employee: EmployeeDto((employeeAge > 30 && employeeAge <= 65) && (monthlyIncome > 20000.00 && monthlyIncome < 40000.00) )
    then
        modify($employee){
            setTax(25.0),
            setNetMonthlyIncome($employee.getMonthlyIncome() - ($employee.getMonthlyIncome() * 0.25)),
            setObservation("Applied Tax of 25.0%")
        }
end

