package mz.co.quankee.drools.tax.calculator;

import mz.co.quankee.drools.tax.calculator.domain.dto.EmployeeDto

dialect  "java"

rule "Validate Age - Minor"
    when
        $employee: EmployeeDto( employeeAge < 18 )
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome(0.0),
            setObservation("Employee is a minor. Not allowed to work")
        }
end

rule "Validate Age - Retired"
    when
        $employee: EmployeeDto( employeeAge > 65 )
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome(179990.0),
            setObservation("Employee is retired.")
        }
end

rule "Calculate Salary for 18 with less than 10000.00"
    when
        $employee: EmployeeDto( employeeAge == 18 && monthlyIncome < 10000.00)
    then
        modify($employee){
            setTax(0.0),
            setNetMonthlyIncome($employee.getMonthlyIncome()),
            setObservation("No taxes apply for this employee")
        }
end

rule "Calculate Salary for 18 with income between 10000.00 and 20000.00"
    when
        $employee: EmployeeDto( employeeAge == 18 && (monthlyIncome > 10000.00 && monthlyIncome < 20000.00) )
    then
        modify($employee){
            setTax(10.0),
            setNetMonthlyIncome($employee.getMonthlyIncome() - ($employee.getMonthlyIncome() * 0.1)),
            setObservation("Applied Tax of 10.0%")
        }
end

