DROP SCHEMA IF EXISTS QUANKEE_DEMO CASCADE;

-- create schema
CREATE SCHEMA IF NOT EXISTS QUANKEE_DEMO;

-- Drop Tables
DROP TABLE IF EXISTS QUANKEE_DEMO.EMPLOYEE;

-- CREATE TABLES
CREATE TABLE QUANKEE_DEMO.EMPLOYEE (
    EMPLOYEE_ID VARCHAR(20),
    EMPLOYEE_NAME VARCHAR(100),
    BIRTHDATE DATE,
    MONTHLY_INCOME NUMERIC(14,2),
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMPLOYEE_ID)
);